on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
    - uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"
        cache: pip
    - uses: extractions/setup-just@v3
    - run: just setup-python
    - run: just lint-python
